// Sample data for all health record features
export const sampleUser = {
  uid: "demo-user-001",
  email: "demo@example.com",
  displayName: "Rajesh Kumar",
  phone: "+91 9876543210",
  aadhaar: "1234-5678-9012",
  address: "123 Main Street, Kochi, Kerala 682001",
  emergencyContact: {
    name: "Priya Kumar",
    phone: "+91 9876543211",
    relation: "Wife",
  },
  language: "en",
  profileComplete: true,
  approvalStatus: "approved",
  createdAt: "2024-01-15T10:30:00Z",
}

export const sampleHealthRecords = [
  {
    id: "hr-001",
    type: "Blood Test",
    date: "2024-01-20",
    hospital: "Kochi Medical Center",
    doctor: "Dr. Sarah Johnson",
    results: "Normal",
    documents: ["blood-test-report.pdf"],
    notes: "All parameters within normal range",
  },
  {
    id: "hr-002",
    type: "X-Ray",
    date: "2024-01-18",
    hospital: "Kerala General Hospital",
    doctor: "Dr. Amit Sharma",
    results: "Clear",
    documents: ["chest-xray.jpg"],
    notes: "No abnormalities detected",
  },
  {
    id: "hr-003",
    type: "Vaccination",
    date: "2024-01-15",
    hospital: "Primary Health Center",
    doctor: "Dr. Meera Nair",
    results: "Completed",
    documents: ["vaccination-certificate.pdf"],
    notes: "COVID-19 booster dose administered",
  },
]

export const sampleAppointments = [
  {
    id: "apt-001",
    type: "General Checkup",
    date: "2024-02-15",
    time: "10:00 AM",
    hospital: "Kochi Medical Center",
    doctor: "Dr. Sarah Johnson",
    status: "confirmed",
    notes: "Annual health checkup",
  },
  {
    id: "apt-002",
    type: "Dental Checkup",
    date: "2024-02-20",
    time: "2:30 PM",
    hospital: "Smile Dental Clinic",
    doctor: "Dr. Ravi Menon",
    status: "pending",
    notes: "Routine dental examination",
  },
  {
    id: "apt-003",
    type: "Eye Examination",
    date: "2024-02-25",
    time: "11:15 AM",
    hospital: "Vision Care Center",
    doctor: "Dr. Lakshmi Pillai",
    status: "confirmed",
    notes: "Vision screening",
  },
]

export const sampleVaccinations = [
  {
    id: "vac-001",
    name: "COVID-19 Booster",
    date: "2024-01-15",
    nextDue: "2024-07-15",
    hospital: "Primary Health Center",
    batchNumber: "COV-2024-001",
    status: "completed",
  },
  {
    id: "vac-002",
    name: "Hepatitis B",
    date: "2023-12-10",
    nextDue: "2024-12-10",
    hospital: "Kerala General Hospital",
    batchNumber: "HEP-2023-045",
    status: "completed",
  },
  {
    id: "vac-003",
    name: "Tetanus",
    date: "2023-11-05",
    nextDue: "2033-11-05",
    hospital: "Community Health Center",
    batchNumber: "TET-2023-089",
    status: "completed",
  },
]

export const sampleReminders = [
  {
    id: "rem-001",
    title: "Take Blood Pressure Medication",
    description: "Take Amlodipine 5mg after breakfast",
    time: "09:00 AM",
    frequency: "daily",
    isActive: true,
    nextReminder: "2024-02-01T09:00:00Z",
  },
  {
    id: "rem-002",
    title: "Doctor Appointment",
    description: "General checkup with Dr. Sarah Johnson",
    time: "10:00 AM",
    frequency: "once",
    isActive: true,
    nextReminder: "2024-02-15T10:00:00Z",
  },
  {
    id: "rem-003",
    title: "Exercise Routine",
    description: "30 minutes morning walk",
    time: "06:30 AM",
    frequency: "daily",
    isActive: true,
    nextReminder: "2024-02-01T06:30:00Z",
  },
]

export const sampleHealthMetrics = [
  {
    date: "2024-01-25",
    weight: 72.5,
    bloodPressure: { systolic: 120, diastolic: 80 },
    heartRate: 75,
    temperature: 98.6,
    bloodSugar: 95,
  },
  {
    date: "2024-01-20",
    weight: 72.8,
    bloodPressure: { systolic: 118, diastolic: 78 },
    heartRate: 72,
    temperature: 98.4,
    bloodSugar: 92,
  },
  {
    date: "2024-01-15",
    weight: 73.0,
    bloodPressure: { systolic: 122, diastolic: 82 },
    heartRate: 78,
    temperature: 98.7,
    bloodSugar: 98,
  },
]

export const sampleAlerts = [
  {
    id: "alert-001",
    type: "medication",
    title: "Medication Reminder",
    message: "Time to take your blood pressure medication",
    timestamp: "2024-02-01T09:00:00Z",
    isRead: false,
    priority: "high",
  },
  {
    id: "alert-002",
    type: "appointment",
    title: "Upcoming Appointment",
    message: "You have a doctor's appointment tomorrow at 10:00 AM",
    timestamp: "2024-02-14T18:00:00Z",
    isRead: false,
    priority: "medium",
  },
  {
    id: "alert-003",
    type: "health",
    title: "Health Tip",
    message: "Remember to stay hydrated and drink at least 8 glasses of water daily",
    timestamp: "2024-02-01T08:00:00Z",
    isRead: true,
    priority: "low",
  },
]

export const sampleMigrationRequests = [
  {
    id: "req-001",
    applicantName: "Rajesh Kumar",
    email: "rajesh@example.com",
    phone: "+91 9876543210",
    aadhaar: "1234-5678-9012",
    fromState: "Tamil Nadu",
    occupation: "Construction Worker",
    submittedDate: "2024-01-25",
    status: "pending",
    documents: ["aadhaar.pdf", "health-certificate.pdf", "employment-letter.pdf"],
    reviewNotes: "",
  },
  {
    id: "req-002",
    applicantName: "Priya Sharma",
    email: "priya@example.com",
    phone: "+91 9876543212",
    aadhaar: "2345-6789-0123",
    fromState: "Karnataka",
    occupation: "Domestic Worker",
    submittedDate: "2024-01-24",
    status: "approved",
    documents: ["aadhaar.pdf", "health-certificate.pdf"],
    reviewNotes: "All documents verified. Approved for entry.",
  },
  {
    id: "req-003",
    applicantName: "Mohammed Ali",
    email: "mohammed@example.com",
    phone: "+91 9876543213",
    aadhaar: "3456-7890-1234",
    fromState: "West Bengal",
    occupation: "Factory Worker",
    submittedDate: "2024-01-23",
    status: "rejected",
    documents: ["aadhaar.pdf"],
    reviewNotes: "Incomplete documentation. Health certificate missing.",
  },
]
